language: node_js
node_js:
  - 12
branches:
  only:
    - master
    - develop
cache: npm
install:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..
script:
  - cd functions
  - npm run build
  - cd ..
deploy:
  - provider: firebase
    project: charitydiscount
    on:
      branch: master
    cleanup: false
    token:
      secure: 'kyLm0v3rIrrSSwEFVVFhh1PV52kuCW38dcQamMuKFiuDzhvSg7l73b395K/LEcv5X4apwHqYSdRf/wFCLxRqxd6bz29Z7vMxLCi9rYBhvAB3nL4ku7ficH1c3kq2p2YLgEKcTK8W83YlxuimXpLfy+rFKYGLojCpwPGP53GugRL1izTdpL6Kmv9VAyggz4WK6b6dpmWgvM0p7FO9MRpgmNmrxnBv2bVjbiqEPNvmGLsN/SaYs/3wbBRNGKW7cFw4a5P+9t8MBMQmqGPzzzGen+rsmw69pcnXLG269efw8FPxAgmvoRhZ1iB829bmCqGOcPpmUfEFiUPNAVu53Q2sJIfdvdE0p3EFDO/xAO/wUy9nbAYzTxJ/4nGupSOMjQR5wrMsGsoMUAx1nMd4UT3hzdGJH8tpo4rE5OPO37BoT2u+TzrCddSGh2wUt5/Bg0au9+jqgSnONTs0lKPq3lVmc1FoIj8/9XGHtxI3yTAPTLfkPb/dyH870iVhHyMU47UxhsXnfyEhNciIS87ieXcnSR8V+Xm7ISnQtnJWrrLz2g7LCwpszbt13ezPuGsG8mMfQ7Abx85ahUv/hlhTv2eY1L/8tC0WHkyB+eDJg6U3xn12fcOANqQQQ9MY0qz9NCe5EWnIgnWuO/wxSvYYRHUpq7YAVmcKcqj/l/oOlQHACAw='
    edge: true
    only: functions
    force: true
  - provider: firebase
    project: charitydiscount-test
    on:
      branch: develop
    cleanup: false
    token:
      secure: 'MNIyRlqOKH6fqAxf9KLd2tesAQx5thH74ZnVuwlc7uxm7b4S7BkjQh08WZA5KYAFWpy4B62dlSNFPRlA/DsDdfBxH+y4WjPQ1TQKrlKBKJxvgD+33uAeSLNY8u1dMETIFJFNZDyPBXemgYVXadiPf4m084J/3uWrbAljoPOYX6rv8F9inzDgDyEZvRpzIe/6vwdvP8L1yVeBke4T1Vn7WkKIJgDl6Y7ctnUToABbgPAwO0cJUbtIjuwSiGWL5vbWXffx6/UYdZ+s4ugxy2NjZwP2mkqmboACJZbMSK8xfCQhV6YXBbFMheFgWRBvhC0ofWh8EzJfUwt97mt+I69DwsZhireuV/osLLL6jFpX43/qaFB3NnoUjlrzu+LctRBWOeVuE5B3qnSivjl4U1eVKvxCMyUxjO8OZ3TlZXisyQrwF4d4yklwfL9mQk9laSlaKQl0nyZHng5vtj96tUX9x6onV2Iq6oUfmvL8s6uvSJXIK82qJsO9cP2M4MgWlrigdyU6quFLqjsO6c9VMiVsmLtAmIyTMk5hTpmqf0sSj3XxolnGkCOMgPUF69dY/wHR8SfaUMt89cx/aj0asP6wlXodsJQJrn42WdphgAUeGIQoEPPL5IOivcrIbWfa5c76osNgMB7BjZefnwYDxXAXyu723UWI2qY+4zKxIH1Wrqg='
    edge: true
    only: functions
    force: true
